# Generated by Django 2.0.2 on 2018-03-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubsu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='email@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(default='ФТФ', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='path',
            field=models.CharField(default='ИСиТ', max_length=250),
            preserve_default=False,
        ),
    ]
