# Generated by Django 2.0.2 on 2018-03-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubsu', '0004_auto_20180309_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
