# Generated by Django 2.0.2 on 2018-03-09 13:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kubsu', '0006_auto_20180309_1309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Profile',
        ),
    ]
